- hosts: localhost
  connection: local

  tasks:

    - name: Pull calculator image from DockerHub
      docker_image:
        name: ruturaj6536/sci-calc:latest
        source: pull

    - name: Remove old container if exists
      docker_container:
        name: sci_calc_container
        state: absent
      ignore_errors: yes

    - name: Run calculator container
      docker_container:
        name: sci_calc_container
        image: ruturaj6536/sci-calc:latest
        state: started
        interactive: true
        tty: true
